services:
  postgres:
    profiles:
      - db
      - all # For when we want to run everything together
    image: pgvector/pgvector:pg16
    container_name: aida-pg-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust # Allow local connections without password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    profiles:
      - api
      - all # For when we want to run everything together
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        required: false # This makes the dependency optional when running api alone

volumes:
  postgres_data:
    name: aida_postgres_data
